# Generated by Django 6.0.2 on 2026-02-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
